# docker-compose generator.
#
# Reads the .env produced by the credential wizard, decides bundled vs
# external Postgres, generates a docker-compose.yml in the deployment
# directory.
#
# Auto-provisions N8N_ENCRYPTION_KEY into the .env if absent (wizard
# doesn't collect it — it's a machine secret, not a user paste).
#
# Side effects:
#   - Appends N8N_ENCRYPTION_KEY to ENV_PATH if missing
#   - Creates DEPLOY_DIR/{data/postgres,config/n8n,config,migrations}
#   - Writes DEPLOY_DIR/docker-compose.yml (overwrites existing with backup)

generate_encryption_key() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    LC_ALL=C tr -dc 'a-f0-9' </dev/urandom 2>/dev/null | head -c 64
  fi
}

# Source an .env file into the current shell's environment.
# Values are single-quoted per the wizard's writer — safe to `source` directly.
_load_env() {
  local env_path="$1"
  if [ ! -f "$env_path" ]; then
    log_error ".env not found at ${env_path}"
    return 1
  fi
  # shellcheck disable=SC1090
  set -a
  source "$env_path"
  set +a
}

_ensure_encryption_key() {
  local env_path="$1"
  if grep -q '^N8N_ENCRYPTION_KEY=' "$env_path" 2>/dev/null; then
    return 0
  fi
  local key
  key="$(generate_encryption_key)"
  printf "\n# Auto-generated by installer compose gen\nN8N_ENCRYPTION_KEY='%s'\n" "$key" >> "$env_path"
  export N8N_ENCRYPTION_KEY="$key"
  log_info "Generated N8N_ENCRYPTION_KEY and appended to ${env_path}"
}

_ensure_deploy_dirs() {
  local deploy_dir="$1"
  mkdir -p \
    "${deploy_dir}/data/postgres" \
    "${deploy_dir}/config/n8n" \
    "${deploy_dir}/config" \
    "${deploy_dir}/migrations"
  log_info "Deployment directories ready under ${deploy_dir}/"
}

# Writes the compose. Assumes env vars are already in scope via _load_env.
_write_compose_file() {
  local target="$1"
  local bundled="${POSTGRES_BUNDLED:-true}"
  local webhook_url="${WEBHOOK_URL:-http://localhost:5678/}"

  if [ -e "$target" ]; then
    mv "$target" "${target}.bak.$(date +%s)"
    log_info "Backed up existing compose → ${target}.bak.<timestamp>"
  fi

  {
    cat <<'HEADER'
# Aerys deployment — generated by installer.
# DO NOT edit directly if you plan to re-run the installer — modify the .env
# and regenerate (./install.sh --compose-only) instead.

services:
HEADER

    if [ "$bundled" = "true" ]; then
      cat <<POSTGRES_BLOCK
  postgres:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      POSTGRES_USER: \${POSTGRES_USER}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
      POSTGRES_DB: n8n
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U \${POSTGRES_USER} -d n8n']
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 60s

POSTGRES_BLOCK
    fi

    cat <<'N8N_BLOCK_TOP'
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
N8N_BLOCK_TOP

    cat <<N8N_ENV
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: \${POSTGRES_HOST}
      DB_POSTGRESDB_PORT: \${POSTGRES_PORT}
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: \${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: \${POSTGRES_PASSWORD}
      N8N_ENCRYPTION_KEY: \${N8N_ENCRYPTION_KEY}
      EXECUTIONS_DATA_PRUNE: "true"
      EXECUTIONS_DATA_MAX_AGE: "720"
      EXECUTIONS_DATA_PRUNE_MAX_COUNT: "10000"
      N8N_SECURE_COOKIE: "false"
      N8N_COMMUNITY_PACKAGES_ENABLED: "true"
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: "true"
      NODE_FUNCTION_ALLOW_BUILTIN: "fs"
      NODE_OPTIONS: "--max-old-space-size=1536"
      GENERIC_TIMEZONE: "\${GENERIC_TIMEZONE:-UTC}"
      WEBHOOK_URL: "${webhook_url}"
N8N_ENV

    cat <<'N8N_BLOCK_BOTTOM'
    ports:
      - "5678:5678"
    volumes:
      - ./config/n8n:/home/node/.n8n
      - ./config:/home/node/aerys-config:ro
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
N8N_BLOCK_BOTTOM

    if [ "$bundled" = "true" ]; then
      cat <<'DEPENDS'
    depends_on:
      postgres:
        condition: service_healthy
DEPENDS
    fi

  } > "$target"

  log_success "Wrote ${target}"
}

# --- Orchestrator -------------------------------------------------------

generate_docker_compose() {
  local env_path="${1:-.env}"
  local deploy_dir="${2:-.}"

  if ! _load_env "$env_path"; then
    return 1
  fi

  _ensure_encryption_key "$env_path"
  # Reload so N8N_ENCRYPTION_KEY is in scope even if it was just appended.
  _load_env "$env_path" >/dev/null 2>&1 || true

  _ensure_deploy_dirs "$deploy_dir"

  local compose_target="${deploy_dir}/docker-compose.yml"
  _write_compose_file "$compose_target"

  # Docker Compose auto-loads .env from the same directory as
  # docker-compose.yml. If the user kept .env elsewhere, drop a copy
  # into deploy_dir so `docker compose up` works without --env-file.
  local env_abs env_in_deploy
  env_abs="$(cd "$(dirname "$env_path")" && pwd)/$(basename "$env_path")"
  env_in_deploy="$(cd "$deploy_dir" && pwd)/.env"
  if [ "$env_abs" != "$env_in_deploy" ]; then
    cp "$env_path" "$env_in_deploy"
    chmod 600 "$env_in_deploy"
    log_info "Copied .env into ${deploy_dir}/ so docker compose picks it up automatically"
  fi

  log_section "Compose generated"
  log_info "Deployment directory: ${deploy_dir}"
  log_info "Config: ${compose_target}"
  log_info "To start: (cd ${deploy_dir} && docker compose up -d)"
  log_info "To stop:  (cd ${deploy_dir} && docker compose down)"
  return 0
}
